#!/bin/sh
# Base44 development entrypoint for the "Among Kids" Android app.
#
# An Android app cannot run inside a browser, and this sandbox has no KVM for an
# emulator, so the preview shows the app's REAL Compose screens: they are rendered
# headlessly with the project's own Robolectric + Roborazzi setup (the same setup
# the repository already uses for app/src/test/screenshots) into PNGs that the
# nginx service serves on port 3000.
#
# This script builds the APK, renders the screens, and then keeps watching the
# sources so an edit is re-rendered and appears in the preview automatically.
set -eu

WORKSPACE="${WORKSPACE:-/workspace}"
OUT="${PREVIEW_OUT_DIR:-/preview-out}"
SCREEN_TAG="com.example.preview.PreviewCaptureTest"

mkdir -p "$OUT"

manifest() { # $1 = stage, $2 = message
  printf '{"stage": "%s", "message": "%s", "updatedAt": %s}\n' "$1" "$2" "$(date +%s)" > "$OUT/manifest.json"
}

build_and_render() {
  if ! gradle --console=plain :app:assembleDebug; then
    manifest "error" "Falha ao compilar o app - veja os logs do servico android"
    return 1
  fi
  manifest "rendering" "Renderizando as telas reais do app (Robolectric + Roborazzi)..."
  if ! gradle --console=plain :app:recordRoborazziDebug --tests "$SCREEN_TAG" --rerun-tasks; then
    manifest "error" "Falha ao renderizar as telas - veja os logs do servico android"
    return 1
  fi
  touch "$OUT/.ready"
  manifest "ready" "Telas renderizadas a partir do codigo atual"
  return 0
}

cd "$WORKSPACE"

# The debug signing config points at ${rootDir}/debug.keystore, which is gitignored and
# normally generated by Android Studio. Create the standard debug keystore if it is absent.
if [ ! -f "$WORKSPACE/debug.keystore" ]; then
  keytool -genkeypair -keystore "$WORKSPACE/debug.keystore" -storepass android -keypass android \
    -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 \
    -dname "CN=Android Debug,O=Android,C=US" > /dev/null 2>&1
  echo "created $WORKSPACE/debug.keystore for debug signing"
fi

manifest "starting" "Preparando o ambiente Android - a primeira execucao baixa o SDK e as dependencias"
build_and_render || true

# Fingerprint of everything that can change the rendered screens.
snapshot() {
  find app/src gradle ./*.kts ./*.properties -type f -printf '%T@ %p\n' 2>/dev/null | sort | md5sum
}

last="$(snapshot)"
while true; do
  sleep 5
  current="$(snapshot)"
  [ "$current" = "$last" ] && continue
  last="$current"
  manifest "rendering" "Codigo alterado - recompilando e renderizando novamente..."
  build_and_render || true
done
